version: '3'

services:
  app:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    container_name: crater-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
     # - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    networks:
      - crater

  db:
    image: mariadb:10.11
    container_name: crater-db
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: root
    networks:
      - crater

  nginx:
    image: nginx:1.17-alpine
    container_name: crater-nginx
    restart: unless-stopped
    volumes:
      # - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crater
      - public_net

  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    container_name: crater-cron
    networks:
      - crater

volumes:
  db:

networks:
  crater:
    driver: bridge
  public_net:
    external: true
